### ISSUE TITLE
Can't scroll through a profile on soundcloud

### ISSUE THREAD

**Issue by Nekothegamer** [migalmoreno/tubo#17]
i can't see or scroll through a library on a soundcloud profile with more than 20 songs 

![bruh](https://github.com/migalmoreno/tubo/assets/112352776/f3e9fee7-a267-4e81-a7e9-f6a67f0237ce)

![larger image so that you can understand better](https://github.com/migalmoreno/tubo/assets/112352776/a1f80f51-334d-4b7b-8a07-f27a8fc56298)

**Comment by migalmoreno** [comment]
Hi! Are you on a touchscreen device? This is a known bug on mobile, but on desktop you should be able to scroll to the end and for it to load paginated results. I'll try to give it a shot this weekend, otherwise I'll temporarily add a "Load More" button.

**Comment by Nekothegamer** [comment]
> on desktop you should be able to scroll to the end and for it to load paginated result


that's the thing, that doesn't happen, i scroll to the bottom of the page and no paginated results load, and there isn't even any "load more" button to load them anyway, your suggestion adding is the most sensible option

**Comment by migalmoreno** [comment]
@Nekothegamer Addressed with ea77d66. Scroll pagination should work fine now, at least it does for me now that I've tried it on mobile. If you can please confirm if this is the case for you as well.

**Comment by migalmoreno** [comment]
@Nekothegamer Closing as I haven't heard back from you and this doesn't seem to be an issue anymore.

**Comment by Nekothegamer** [comment]
oh yeah sorry if i haven't replied, yes it works now thank you ❤️
