### ISSUE TITLE
Self-hosting with Docker issues

### ISSUE THREAD

**Issue by xbdmHQ** [migalmoreno/tubo#2]
When i install with docker i get the issue below and here is the instance: https://tv.whateveritworks.org/

```
<!DOCTYPE html>
<html><head><meta charset="UTF-8"><meta content="width=device-width, initial-scale=1" name="viewport"><title>Tubo</title><link href="#" rel="shortcut icon"><link href="/css/tubo.css" rel="stylesheet" type="text/css"></head><body><div id="app"></div><script src="/js/main.js" type="text/javascript"></script><script>tubo.core.init();</script></body></html>
```

docker logs

```
Server running in port 3000
```

**Comment by xbdmHQ** [comment]
@migalmoreno

**Comment by xbdmHQ** [comment]
@migalmoreno

**Comment by migalmoreno** [comment]
Hi! I can't reproduce this issue with the current Docker scripts. Would you mind testing if this might have been caused by your changes in #4?

**Comment by xbdmHQ** [comment]
> Hi! I can't reproduce this issue with the current Docker scripts. Would you mind testing if this might have been caused by your changes in #4?

No, the error is right there seems you misconfigured something in the code.

**Comment by xbdmHQ** [comment]
@migalmoreno

**Comment by migalmoreno** [comment]
Sure. I'll have a look at this as soon as possible

**Comment by migalmoreno** [comment]
I tested this with your fork and everything seems to be working fine on my end, the app is deployed on localhost on port 3080. To reproduce this I removed all my local containers/images/volumes, cloned your fork, cd'ed into it and ran `docker-compose up -d` at the top level. 

Only reason I can see this not working is if you're missing the `main.js` entry point file, or perhaps if you've disabled JavaScript in your browser. What does `docker exec -ti tubo /bin/ls /app/resources/public/js` yield for you?

**Comment by xbdmHQ** [comment]
> I tested this with your fork and everything seems to be working fine on my end, the app is deployed on localhost on port 3080. To reproduce this I removed all my local containers/images/volumes, cloned your fork, cd'ed into it and ran `docker-compose up -d` at the top level.
> 
> Only reason I can see this not working is if you're missing the `main.js` entry point file, or perhaps if you've disabled JavaScript in your browser. What does `docker exec -ti tubo /bin/ls /app/resources/public/js` yield for you?

```
main.js       manifest.edn
```

**Comment by migalmoreno** [comment]
Hmm, that's as expected. Can your perhaps try your fork in your local dev environment? So we can discard it's something server-specific
