### ISSUE TITLE
YouTube Playlist support 

### ISSUE THREAD

**Issue by toyboatcash** [migalmoreno/tubo#24]
I can't find or load playlists for YouTube. Here is the link I used. http://localhost:3000/stream?url=https%3A%2F%2Fwww.youtube.com/playlist?list=PLMC9KNkIncKtPzgY-5rmhvj7fax8fdxoj
![image](https://github.com/migalmoreno/tubo/assets/64506027/bf91c927-ba3f-4e25-9e42-a48a49354504)

**Comment by migalmoreno** [comment]
Please use the `/playlist?url=<PLAYLIST_URL>` endpoint for playlists and not `/stream`.
