### ISSUE TITLE
SoundCloud Playlist support 

### ISSUE THREAD

**Issue by toyboatcash** [migalmoreno/tubo#27]
I would like to request SoundCloud Playlist support.

http://localhost:3000/stream?url=https%3A%2F%2Fsoundcloud.com/rickyrozaymmg/aston-martin-music-album-1/sets
https://soundcloud.com/rickyrozaymmg/aston-martin-music-album-1/sets

http://localhost:3000/stream?url=https%3A%2F%2Fsoundcloud.com/sets/kitboga
https://soundcloud.com/3siamesecats/sets/kitboga

http://localhost:3000/stream?url=https%3A%2F%2Fsoundcloud.com/sets?q=kitboga
https://soundcloud.com/search/sets?q=kitboga

**Comment by migalmoreno** [comment]
As in #28, sets are already supported as "playlists", so the corresponding playlist URL would be https://tubo.migalmoreno.com/playlist?url=https%3A%2F%2Fsoundcloud.com%2F3siamesecats%2Fsets%2Fkitboga.
