### ISSUE TITLE
Add SoundCloud Album support and error page  "No available streams"

### ISSUE THREAD

**Issue by toyboatcash** [migalmoreno/tubo#28]
I would like to have SoundCloud Album support.

http://localhost:3000/channel?url=https%3A%2F%2Fsoundcloud.com/microneesia/albums
https://soundcloud.com/microneesia/albums

http://localhost:3000/channel?url=https%3A%2F%2Fsoundcloud.com/albums?q=kitboga shows a page with "No available streams" 
![image](https://github.com/migalmoreno/tubo/assets/64506027/ba6c5682-6444-4bcd-8e59-1801fda46ec9)
https://soundcloud.com/search/albums?q=kitboga
![image](https://github.com/migalmoreno/tubo/assets/64506027/3586deea-9f25-407c-8c91-93311d216057)

**Comment by migalmoreno** [comment]
SoundCloud albums are considered "playlists", so the corresponding album would be https://tubo.migalmoreno.com/playlist?url=https%3A%2F%2Fsoundcloud.com%2Fmicroneesia%2Fsets%2Fboga-beatz-v-9. What I do want to add is support for channel tabs so it's easier to find the different types of content from a channel, as per #1.
