### ISSUE TITLE
media.ccc.de tag support  

### ISSUE THREAD

**Issue by toyboatcash** [migalmoreno/tubo#31]
Add tag support for media.ccc.de 

Example link localhost:3000/channel?url=https%3A%2F%2Fmedia.ccc.de%2Ftags%2F37c3
Direct https://media.ccc.de/tags/37c3

I think I have the URL correct, let me know if I have the wrong URL.

**Comment by migalmoreno** [comment]
Tags are not currently supported in any service, so I'm closing this in favor of #26
