### ISSUE TITLE
Support media.ccc.de Browse by category

### ISSUE THREAD

**Issue by toyboatcash** [migalmoreno/tubo#32]
Support Browse by category
https://media.ccc.de/b
![image](https://github.com/migalmoreno/tubo/assets/64506027/6ac9a4ee-ec70-4b6f-861a-92f11a1668e0)
http://localhost:3000/playlist?url=https%3A%2F%2Fslift.bandcamp.com%2Fb
http://localhost:3000/playlist?url=https%3A%2F%2Fslift.bandcamp.com/b

**Comment by migalmoreno** [comment]
This needs to be added upstream for sure, so if you can, please raise a feature request there https://github.com/TeamNewPipe/NewPipeExtractor/issues. Currently, only conferences are supported.
