### ISSUE TITLE
Bug Bandcamp Pre-order Digital album shows links as null

### ISSUE THREAD

**Issue by toyboatcash** [migalmoreno/tubo#33]
Bandcamp Pre-order Digital Album shows up as null http://localhost:3000/stream?url=https%3A%2F%2Fkhruangbin.bandcamp.com%2Fnull

https://khruangbin.bandcamp.com/album/a-la-sala
http://localhost:3000/playlist?url=https%3A%2F%2Fkhruangbin.bandcamp.com%2Falbum%2Fa-la-sala

**Comment by migalmoreno** [comment]
I can reproduce this too, but it seems to be a problem in the extractor. I'm experiencing a similar error in the Newpipe app.
