### ISSUE TITLE
Bandcamp video page support 

### ISSUE THREAD

**Issue by toyboatcash** [migalmoreno/tubo#34]
Add bandcamp.com video support 
http://localhost:3000/channel?url=https%3A%2F%2Farmandhammer.bandcamp.com%2Fvideo
http://localhost:3000/channel?url=https%3A%2F%2Farmandhammer.bandcamp.com/video
https://armandhammer.bandcamp.com/video
![image](https://github.com/migalmoreno/tubo/assets/64506027/01125bcb-db1d-4997-a717-bc036b8ee2b0)

video link example seems to only work on the page with the embed. Embed Also redirects https://bandcamp.com/video_frame?video_id=85357,35071&band_id=2425264419

**Comment by migalmoreno** [comment]
Again, as per #32, this issue belongs to the extractor, so please raise it there. I'll be happy to implement it once support for it is merged, but I'm closing it for now.
