### ISSUE TITLE
in Soundcloud most Tracks over 1 hour,  only minutes are displayed

### ISSUE THREAD

**Issue by nordisch-dev** [migalmoreno/tubo#35]
In the search results, most of the tracks in soundcloud, only minutes are displayed, (i think there is no issue in yt).
![Screenshot_2024-01-23_17-25-53](https://github.com/migalmoreno/tubo/assets/78126468/0b0ac28e-4833-47bb-a7a3-2a4a7b2393d0)
![bug](https://github.com/migalmoreno/tubo/assets/78126468/9e59e880-4f33-4451-999b-9e856da08c81)

**Comment by migalmoreno** [comment]
Thanks for the catch! I pushed a fix in f396fe9
